/*
# Seed Sample Data for Flavours of Palnadu

This migration populates the database with sample product categories, products,
testimonials, and FAQs to make the store functional immediately.

1. Categories: Mango Pickles, Gongura Pickles, Lemon Pickles, Garlic Pickles,
   Murukulu, Chekkalu, Traditional Snacks, Combo Packs.
2. Products: 20+ authentic homemade Andhra food products with realistic prices.
3. Testimonials: 6 customer testimonials for the homepage.
4. FAQs: 8 common questions.
*/

-- Insert categories
INSERT INTO categories (name, slug, description, sort_order) VALUES
  ('Mango Pickles', 'mango-pickles', 'Authentic Andhra mango pickles made with handpicked raw mangoes and traditional spices', 1),
  ('Gongura Pickles', 'gongura-pickles', 'Traditional gongura (sorrel leaf) pickles - a signature taste of Andhra Pradesh', 2),
  ('Lemon Pickles', 'lemon-pickles', 'Tangy and spicy lemon pickles prepared with farm-fresh lemons', 3),
  ('Garlic Pickles', 'garlic-pickles', 'Rich garlic pickles with a bold, authentic Andhra flavor', 4),
  ('Murukulu', 'murukulu', 'Crispy, crunchy rice flour snacks perfect for tea time', 5),
  ('Chekkalu', 'chekkalu', 'Savory rice crackers in traditional and spicy flavors', 6),
  ('Traditional Snacks', 'traditional-snacks', 'A variety of homemade Andhra snacks made from family recipes', 7),
  ('Combo Packs', 'combo-packs', 'Curated bundles of our best-selling pickles and snacks at great value', 8)
ON CONFLICT (slug) DO NOTHING;

-- Insert products
INSERT INTO products (name, slug, description, ingredients, price, compare_price, weight_options, category_id, images, featured, bestseller, stock, rating, review_count, seo_title, seo_description) VALUES
  ('Avakaya Mango Pickle', 'avakaya-mango-pickle', 'The crown jewel of Andhra pickles - Avakaya is made with raw mangoes, mustard powder, red chili powder, and sesame oil. This traditional recipe has been passed down through generations in our family. Each batch is sun-dried and hand-mixed to ensure the perfect balance of spice and tang.', 'Raw mangoes, Mustard powder, Red chili powder, Fenugreek, Salt, Sesame oil, Turmeric', 249, 299, ARRAY['250g', '500g', '1kg'], (SELECT id FROM categories WHERE slug = 'mango-pickles'), ARRAY['https://images.pexels.com/photos/4110541/pexels-photo-4110541.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/2286776/pexels-photo-2286776.jpeg?auto=compress&cs=tinysrgb&w=800'], true, true, 100, 4.8, 42, 'Avakaya Mango Pickle - Authentic Andhra Homemade Pickle', 'Buy traditional Avakaya mango pickle made with fresh raw mangoes and family recipe. Spicy, tangy, and authentic Andhra taste.'),
  ('Mango Thokku Pickle', 'mango-thokku-pickle', 'A luscious, semi-dry mango pickle made with grated raw mangoes and aromatic spices. The rich texture and intense flavor make it a perfect companion for rice, roti, and even dosa.', 'Grated raw mangoes, Red chili powder, Mustard seeds, Fenugreek, Salt, Sesame oil, Garlic', 199, 249, ARRAY['250g', '500g'], (SELECT id FROM categories WHERE slug = 'mango-pickles'), ARRAY['https://images.pexels.com/photos/4033313/pexels-photo-4033313.jpeg?auto=compress&cs=tinysrgb&w=800'], true, false, 80, 4.6, 28, 'Mango Thokku Pickle - Grated Mango Andhra Pickle', 'Delicious mango thokku pickle made with fresh grated mangoes and traditional spices. Perfect for rice and roti.'),
  ('Gongura Red Chili Pickle', 'gongura-red-chili-pickle', 'The legendary gongura pickle is the soul of Andhra cuisine. Made with fresh sorrel leaves and fiery red chilies, this pickle delivers an unforgettable tangy-spicy punch that Andhra food lovers crave.', 'Gongura (sorrel leaves), Red chilies, Mustard seeds, Fenugreek, Salt, Sesame oil, Garlic', 229, 279, ARRAY['250g', '500g', '1kg'], (SELECT id FROM categories WHERE slug = 'gongura-pickles'), ARRAY['https://images.pexels.com/photos/2286776/pexels-photo-2286776.jpeg?auto=compress&cs=tinysrgb&w=800'], true, true, 120, 4.9, 56, 'Gongura Red Chili Pickle - Authentic Andhra Sorrel Leaf Pickle', 'Authentic gongura pickle made with fresh sorrel leaves and red chilies. The signature taste of Andhra Pradesh.'),
  ('Gongura Dal Pickle', 'gongura-dal-pickle', 'A unique blend of gongura leaves and roasted lentils, creating a crunchy, nutty pickle with the signature tang of gongura. This is a rare specialty that is hard to find outside of Andhra homes.', 'Gongura leaves, Toor dal, Bengal gram, Red chilies, Mustard seeds, Salt, Sesame oil', 219, 269, ARRAY['250g', '500g'], (SELECT id FROM categories WHERE slug = 'gongura-pickles'), ARRAY['https://images.pexels.com/photos/4110541/pexels-photo-4110541.jpeg?auto=compress&cs=tinysrgb&w=800'], false, false, 60, 4.5, 19, 'Gongura Dal Pickle - Crunchy Lentil and Sorrel Pickle', 'Unique gongura dal pickle with crunchy lentils and tangy sorrel leaves. A rare Andhra specialty.'),
  ('Spicy Lemon Pickle', 'spicy-lemon-pickle', 'Whole lemons preserved in a fiery blend of spices and salt. This pickle is sun-cured for weeks to develop its deep, complex flavor. The burst of citrus and heat is unmatched.', 'Whole lemons, Red chili powder, Mustard seeds, Fenugreek, Salt, Sesame oil, Turmeric', 189, 229, ARRAY['250g', '500g', '1kg'], (SELECT id FROM categories WHERE slug = 'lemon-pickles'), ARRAY['https://images.pexels.com/photos/4033313/pexels-photo-4033313.jpeg?auto=compress&cs=tinysrgb&w=800'], true, false, 90, 4.7, 35, 'Spicy Lemon Pickle - Whole Lemon Andhra Pickle', 'Fiery whole lemon pickle sun-cured with traditional spices. Authentic Andhra taste with citrus and heat.'),
  ('Lemon Thokku Pickle', 'lemon-thokku-pickle', 'Grated lemon peel and pulp blended with aromatic spices to create a thick, fragrant pickle. The lemon thokku is milder than the whole lemon pickle but equally delightful.', 'Grated lemon, Red chilies, Mustard seeds, Fenugreek, Salt, Sesame oil, Ginger', 179, 219, ARRAY['250g', '500g'], (SELECT id FROM categories WHERE slug = 'lemon-pickles'), ARRAY['https://images.pexels.com/photos/2286776/pexels-photo-2286776.jpeg?auto=compress&cs=tinysrgb&w=800'], false, false, 70, 4.4, 22, 'Lemon Thokku Pickle - Grated Lemon Andhra Pickle', 'Fragrant lemon thokku pickle made with grated lemon and aromatic spices. Milder and delightful.'),
  ('Garlic Chili Pickle', 'garlic-chili-pickle', 'Whole garlic pods marinated in a rich chili and spice blend. This pickle is a garlic lover''s dream - bold, intense, and packed with flavor. The garlic becomes soft and infused with spice over time.', 'Whole garlic, Red chili powder, Mustard seeds, Fenugreek, Salt, Sesame oil, Tamarind', 239, 289, ARRAY['250g', '500g', '1kg'], (SELECT id FROM categories WHERE slug = 'garlic-pickles'), ARRAY['https://images.pexels.com/photos/4110541/pexels-photo-4110541.jpeg?auto=compress&cs=tinysrgb&w=800'], true, true, 110, 4.8, 48, 'Garlic Chili Pickle - Whole Garlic Andhra Pickle', 'Bold garlic chili pickle with whole garlic pods marinated in rich spices. Intense Andhra flavor.'),
  ('Garlic Thokku Pickle', 'garlic-thokku-pickle', 'Finely minced garlic sauteed with spices and tamarind to create a rich, thick pickle. The garlic thokku is versatile and pairs wonderfully with both South Indian and North Indian dishes.', 'Minced garlic, Red chilies, Mustard seeds, Tamarind, Salt, Sesame oil, Curry leaves', 229, 279, ARRAY['250g', '500g'], (SELECT id FROM categories WHERE slug = 'garlic-pickles'), ARRAY['https://images.pexels.com/photos/4033313/pexels-photo-4033313.jpeg?auto=compress&cs=tinysrgb&w=800'], false, false, 65, 4.6, 25, 'Garlic Thokku Pickle - Minced Garlic Andhra Pickle', 'Rich garlic thokku pickle with minced garlic, tamarind, and spices. Versatile and flavorful.'),
  ('Traditional Murukulu', 'traditional-murukulu', 'Crispy, spiral-shaped rice flour snacks made with urad dal and sesame seeds. Deep-fried to golden perfection, these murukulu are the quintessential Andhra tea-time snack. Each piece is handmade for that perfect crunch.', 'Rice flour, Urad dal flour, Sesame seeds, Cumin, Asafoetida, Salt, Oil', 149, 189, ARRAY['250g', '500g'], (SELECT id FROM categories WHERE slug = 'murukulu'), ARRAY['https://images.pexels.com/photos/6066050/pexels-photo-6066050.jpeg?auto=compress&cs=tinysrgb&w=800'], true, false, 150, 4.7, 33, 'Traditional Murukulu - Crispy Andhra Rice Snacks', 'Crispy handmade murukulu snacks made with rice flour and urad dal. Perfect Andhra tea-time crunch.'),
  ('Spicy Murukulu', 'spicy-murukulu', 'For those who like a kick, these murukulu are infused with extra red chili and black pepper. The heat builds gradually with each bite, making them irresistible for spice lovers.', 'Rice flour, Urad dal flour, Red chili powder, Black pepper, Sesame seeds, Cumin, Salt, Oil', 159, 199, ARRAY['250g', '500g'], (SELECT id FROM categories WHERE slug = 'murukulu'), ARRAY['https://images.pexels.com/photos/6066050/pexels-photo-6066050.jpeg?auto=compress&cs=tinysrgb&w=800'], false, true, 120, 4.8, 41, 'Spicy Murukulu - Hot Chili Andhra Rice Snacks', 'Extra spicy murukulu with red chili and black pepper. Fiery Andhra tea-time snack for heat lovers.'),
  ('Chekkalu - Plain', 'chekkalu-plain', 'Thin, crispy rice crackers that are perfectly salted and irresistibly crunchy. These traditional chekkalu are made by pressing rice dough and deep-frying until light and crisp.', 'Rice flour, Bengal gram, Salt, Cumin, Asafoetida, Oil', 139, 169, ARRAY['250g', '500g'], (SELECT id FROM categories WHERE slug = 'chekkalu'), ARRAY['https://images.pexels.com/photos/6066050/pexels-photo-6066050.jpeg?auto=compress&cs=tinysrgb&w=800'], true, false, 130, 4.5, 27, 'Chekkalu Plain - Crispy Andhra Rice Crackers', 'Thin crispy rice crackers - traditional chekkalu made with rice flour and spices. Perfectly crunchy.'),
  ('Chekkalu - Spicy', 'chekkalu-spicy', 'These chekkalu are seasoned with red chili powder and green chilies for a bold, spicy flavor. The heat is balanced with the natural sweetness of rice, making them addictive.', 'Rice flour, Bengal gram, Red chili powder, Green chilies, Salt, Cumin, Oil', 149, 179, ARRAY['250g', '500g'], (SELECT id FROM categories WHERE slug = 'chekkalu'), ARRAY['https://images.pexels.com/photos/6066050/pexels-photo-6066050.jpeg?auto=compress&cs=tinysrgb&w=800'], false, true, 100, 4.6, 31, 'Chekkalu Spicy - Hot Andhra Rice Crackers', 'Spicy chekkalu with red chili and green chilies. Bold, addictive Andhra rice crackers.'),
  ('Sakinalu', 'sakinalu', 'A traditional Andhra festival snack made with rice flour and sesame seeds. These circular, intricate snacks are a labor of love and a hallmark of Andhra culinary tradition. Crispy, nutty, and absolutely delicious.', 'Rice flour, Sesame seeds, Cumin, Ajwain, Salt, Oil', 169, 209, ARRAY['250g', '500g'], (SELECT id FROM categories WHERE slug = 'traditional-snacks'), ARRAY['https://images.pexels.com/photos/6066050/pexels-photo-6066050.jpeg?auto=compress&cs=tinysrgb&w=800'], true, false, 80, 4.7, 24, 'Sakinalu - Traditional Andhra Festival Snack', 'Traditional sakinalu - intricate circular snacks made with rice flour and sesame seeds. Andhra festival specialty.'),
  ('Minapa Sunnundalu', 'minapa-sunnundalu', 'Sweet urad dal laddus made with roasted urad dal flour, jaggery, and ghee. These protein-rich sweets are a healthy Andhra tradition and a perfect energy snack for children and elders alike.', 'Urad dal flour, Jaggery, Ghee, Cardamom, Cashews', 189, 229, ARRAY['250g', '500g', '1kg'], (SELECT id FROM categories WHERE slug = 'traditional-snacks'), ARRAY['https://images.pexels.com/photos/6066050/pexels-photo-6066050.jpeg?auto=compress&cs=tinysrgb&w=800'], false, true, 90, 4.9, 38, 'Minapa Sunnundalu - Urad Dal Laddu Andhra Sweet', 'Healthy urad dal laddus with jaggery and ghee. Protein-rich Andhra traditional sweet snack.'),
  ('Gavvalu', 'gavvalu', 'Shell-shaped sweet snacks made with rice flour and jaggery syrup. These beautiful gavvalu are handcrafted with precision and have a delightful crunch with a sweet, caramel-like finish.', 'Rice flour, Jaggery, Ghee, Cardamom, Oil', 159, 199, ARRAY['250g', '500g'], (SELECT id FROM categories WHERE slug = 'traditional-snacks'), ARRAY['https://images.pexels.com/photos/6066050/pexels-photo-6066050.jpeg?auto=compress&cs=tinysrgb&w=800'], false, false, 75, 4.6, 20, 'Gavvalu - Shell Shaped Andhra Sweet Snack', 'Beautiful shell-shaped gavvalu made with rice flour and jaggery. Sweet, crunchy Andhra tradition.'),
  ('Pickle Lover Combo', 'pickle-lover-combo', 'The ultimate combo for pickle enthusiasts! Includes our best-selling Avakaya Mango Pickle (500g), Gongura Red Chili Pickle (500g), and Spicy Lemon Pickle (500g). A curated selection of our finest pickles at a special bundle price.', 'Avakaya (500g), Gongura (500g), Lemon Pickle (500g)', 599, 699, ARRAY['1 Pack'], (SELECT id FROM categories WHERE slug = 'combo-packs'), ARRAY['https://images.pexels.com/photos/2286776/pexels-photo-2286776.jpeg?auto=compress&cs=tinysrgb&w=800'], true, true, 50, 4.8, 45, 'Pickle Lover Combo - Best Andhra Pickles Bundle', 'Combo pack of Avakaya, Gongura, and Lemon pickles. Best-selling Andhra pickle bundle at special price.'),
  ('Snacks Fest Combo', 'snacks-fest-combo', 'A delightful assortment of all our traditional snacks - Traditional Murukulu (500g), Chekkalu Spicy (500g), Sakinalu (250g), and Minapa Sunnundalu (250g). Perfect for festivals, gatherings, or simply stocking up your snack cabinet.', 'Murukulu (500g), Chekkalu (500g), Sakinalu (250g), Sunnundalu (250g)', 549, 649, ARRAY['1 Pack'], (SELECT id FROM categories WHERE slug = 'combo-packs'), ARRAY['https://images.pexels.com/photos/6066050/pexels-photo-6066050.jpeg?auto=compress&cs=tinysrgb&w=800'], true, false, 40, 4.7, 29, 'Snacks Fest Combo - Traditional Andhra Snacks Bundle', 'Combo pack of murukulu, chekkalu, sakinalu, and sunnundalu. Perfect Andhra snack assortment for festivals.'),
  ('Grand Palnadu Combo', 'grand-palnadu-combo', 'Experience the full flavors of Palnadu with our grand combo! Includes Avakaya Mango Pickle (500g), Gongura Pickle (500g), Garlic Chili Pickle (250g), Traditional Murukulu (500g), Chekkalu (500g), and Sakinalu (250g). The complete Palnadu experience in one box.', 'Avakaya (500g), Gongura (500g), Garlic (250g), Murukulu (500g), Chekkalu (500g), Sakinalu (250g)', 999, 1199, ARRAY['1 Pack'], (SELECT id FROM categories WHERE slug = 'combo-packs'), ARRAY['https://images.pexels.com/photos/2286776/pexels-photo-2286776.jpeg?auto=compress&cs=tinysrgb&w=800'], true, true, 30, 4.9, 52, 'Grand Palnadu Combo - Complete Andhra Food Experience', 'The complete Palnadu experience with pickles and snacks. Grand combo pack of authentic Andhra homemade food.')
ON CONFLICT (slug) DO NOTHING;

-- Insert testimonials
INSERT INTO testimonials (name, location, rating, comment, featured) VALUES
  ('Ramesh Kumar', 'Hyderabad, Telangana', 5, 'The Avakaya pickle is exactly like my grandmother used to make. I have tried many online pickle brands, but Flavours of Palnadu is the only one that truly captures the authentic Andhra taste. The spice level is perfect and the texture is amazing.', true),
  ('Lakshmi Devi', 'Bangalore, Karnataka', 5, 'I ordered the Grand Palnadu Combo for a family function and everyone loved it. The murukulu were crispy and fresh, and the pickles had that homemade quality you cannot find in supermarkets. Will definitely order again!', true),
  ('Suresh Reddy', 'Chennai, Tamil Nadu', 5, 'The Gongura pickle is outstanding! It reminds me of my mother''s cooking. The packaging is excellent and the delivery was prompt. I have recommended this to all my Andhra friends in Chennai.', true),
  ('Anitha Priya', 'Vijayawada, Andhra Pradesh', 4, 'Great quality snacks. The Minapa Sunnundalu are my favorite - they are soft, sweet, and melt in the mouth. You can taste the ghee and jaggery. A healthy snack option for kids.', true),
  ('Venkatesh Rao', 'Mumbai, Maharashtra', 5, 'I ordered from Flavours of Palnadu for the first time and was impressed by the freshness. The Chekkalu were perfectly salted and crunchy. The product descriptions are accurate and helpful. Customer service is also very responsive.', true),
  ('Padmaja Naidu', 'Delhi, NCR', 4, 'The Garlic Chili Pickle is the best I have ever tasted outside of Andhra. The whole garlic pods are soft and flavorful, and the spice blend is authentic. Love the family business story behind this brand. I will keep supporting them!', true)
ON CONFLICT DO NOTHING;

-- Insert FAQs
INSERT INTO faqs (question, answer, category, sort_order) VALUES
  ('How are your pickles and snacks made?', 'All our products are made using traditional family recipes passed down through generations. We use high-quality, fresh ingredients sourced from local farms in Palnadu. Every batch is prepared in small quantities to ensure quality and authenticity. No artificial preservatives or colors are added.', 'General', 1),
  ('How long do the pickles stay fresh?', 'Our pickles are made with natural preservatives like salt, oil, and spices. When stored in a cool, dry place and handled with a clean, dry spoon, they stay fresh for 6 to 12 months. Always ensure the oil layer covers the pickle to maintain freshness.', 'Products', 2),
  ('What is your delivery time?', 'We process orders within 1-2 business days. Delivery typically takes 3-7 business days depending on your location. We ship across India through reliable courier partners. You will receive a tracking link once your order is dispatched.', 'Shipping', 3),
  ('Do you offer Cash on Delivery?', 'Yes, we offer Cash on Delivery (COD) for orders across India. You can also pay via UPI (GPay, PhonePe, Paytm) and other online payment methods for a seamless checkout experience.', 'Payments', 4),
  ('What is your return policy?', 'Due to the perishable nature of food products, we do not accept returns on opened items. However, if you receive a damaged or incorrect product, please contact us within 24 hours of delivery with photos, and we will arrange a replacement or refund.', 'Returns', 5),
  ('Are your products vegetarian?', 'Yes, all our products are 100% vegetarian. We use only plant-based ingredients in our pickles and snacks. They are suitable for vegetarians and can be enjoyed by people of all dietary preferences.', 'Products', 6),
  ('Can I order in bulk for weddings or events?', 'Absolutely! We offer bulk orders for weddings, festivals, corporate events, and gifting. Contact us via WhatsApp or email with your requirements, and we will provide a custom quote with special packaging options.', 'Orders', 7),
  ('How do I store the snacks after opening?', 'Our snacks should be stored in an airtight container in a cool, dry place after opening. They typically stay fresh for 3-4 weeks after opening. Avoid exposure to moisture and direct sunlight to maintain crispness.', 'Products', 8)
ON CONFLICT DO NOTHING;
